import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PromptInputProvider } from "@/components/ai-elements/prompt-input";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PromptInputProvider>
          {children}
        </PromptInputProvider>
      </body>
    </html>
  );
}
